# Generated by Django 3.0.7 on 2021-07-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=2000)),
            ],
        ),
    ]
