# Generated by Django 3.0.7 on 2021-07-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0003_sent_times'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='checkbox',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
