# Generated by Django 3.0.7 on 2021-07-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0004_sent_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='message1',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
