# Generated by Django 3.0.7 on 2021-07-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0005_sent_message1'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='slt2',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
