# Generated by Django 3.0.7 on 2021-07-12 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0007_auto_20210712_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=10),
        ),
    ]
