# Generated by Django 3.0.7 on 2021-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0008_auto_20210712_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='sent',
            name='date',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
