# Generated by Django 3.0.7 on 2021-07-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0009_sent_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='lastname',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
