# Generated by Django 3.0.7 on 2021-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0010_login_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='email',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
