# Generated by Django 3.0.7 on 2021-07-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0011_login_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='phone',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
