# Generated by Django 3.0.7 on 2021-07-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0013_auto_20210719_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=10),
        ),
    ]
