# Generated by Django 3.0.7 on 2021-07-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mark1', '0014_auto_20210719_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=30),
        ),
    ]
